// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict";
let a = require("./a");
let b = require("./1/test");

console.log(
  "Hello, world!" +
    Object.keys(a)
      .map((k) => `${k} ${a[k]}`)
      .join(""),
);

/*  Not a pure module */
