// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict";
let a = require("./a");
let b = require("./1/test");
let Html = {css:() => {}}
let red = "red"


var pinkColor = "mistyrose";

var pink = Html.css([
      "\n&:hover {\n    color: ",
      ";\n}"
    ], [pinkColor]);



console.log(
  "Hello, world!\n" +
    Object.keys(a)
      .map((k) => `${k} ${a[k]}`)
      .join(""),
);

/*  Not a pure module */
