// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict";

let a = require("./a");
let b = require("./1/test");
let Html = {
  css: () => {}
};
let red = "red";
var pinkColor = "mistyrose";
var pink = "css-1iaf4sr";
console.log("Hello, world!\n" + Object.keys(a).map(k => `${k} ${a[k]}`).join(""));

/*  Not a pure module */
((body, name, value) => {
  if (body) {
    body.style.setProperty(name, value);
  }
  document.addEventListener('DOMContentLoaded', () => {
    document.body.style.setProperty(name, value);
  });
})(document.body, "--kentacss0-0", pinkColor)